# List of tech blog URLs to scrape articles from
TECH_BLOG_URLS = [
    "https://www.docker.com/blog/",
    "https://blog.x.com/engineering/en_us/",
    "https://theguardian.engineering/blog/",
    "https://asana.com/inside-asana/engineering-spotlight/",
    "https://medium.com/groupon-eng/",
    "https://envoy.engineering/",
    "https://engineering.grab.com/",
    "https://www.anthropic.com/engineering/",
    "https://resend.com/blog?category=engineering/",
    "https://www.mintlify.com/blog/",
    "https://cursor.com/blog/",
    "https://groq.com/blog/"
]

    # "https://medium.com/pinterest-engineering",
    # "https://dropbox.tech/",
    # "https://instagram-engineering.com/",
    # "https://openai.com/research/?topics=software-engineering",
    # "https://netflixtechblog.com/",
    # "https://medium.com/airbnb-engineering",
    # "https://aws.amazon.com/blogs/aws/",
    # "https://www.figma.com/blog/engineering/",
    # "https://discord.com/category/engineering/",
    # "https://careersatdoordash.com/engineering-blog/",
    # "https://www.databricks.com/blog/",
    # "https://www.confluent.io/blog/area/technology/",
    # "https://blog.cloudflare.com/",
    # "https://githubengineering.com/",
    # "https://slack.engineering/",
    # "https://www.heroku.com/blog/category/engineering/",
    # "https://www.notion.com/blog/topic/tech/",
    # "https://engineering.fb.com/category/ai-research/",
    # "https://www.rippling.com/blog/topics?topics=engineering/",
    # "https://medium.engineering/",
    # "https://stackoverflow.blog/engineering/",
    # "https://www.algolia.com/blog/",
    # "https://medium.com/paypal-tech/",
    # "https://www.reddit.com/r/RedditEng/",
    # "https://quoraengineering.quora.com/",
    # "https://deliveroo.engineering/",
    # "https://blog.booking.com/",
    # "https://atlassianblog.wpengine.com/",
    # "https://godaddy.github.io/engineering/",
    # "https://evilmartians.com/chronicles",